// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class backpack : Exchange
{
    public backpack (object args = null): base(args) {}

    public async Task<object> publicGetStatus (object parameters = null)
    {
        return await this.callAsync ("publicGetStatus",parameters);
    }

    public async Task<object> publicGetTime (object parameters = null)
    {
        return await this.callAsync ("publicGetTime",parameters);
    }

    public async Task<object> publicGetAssets (object parameters = null)
    {
        return await this.callAsync ("publicGetAssets",parameters);
    }

    public async Task<object> publicGetMarkets (object parameters = null)
    {
        return await this.callAsync ("publicGetMarkets",parameters);
    }

    public async Task<object> publicGetMarket (object parameters = null)
    {
        return await this.callAsync ("publicGetMarket",parameters);
    }

    public async Task<object> publicGetDepth (object parameters = null)
    {
        return await this.callAsync ("publicGetDepth",parameters);
    }

    public async Task<object> publicGetTrades (object parameters = null)
    {
        return await this.callAsync ("publicGetTrades",parameters);
    }

    public async Task<object> publicGetTradesHistory (object parameters = null)
    {
        return await this.callAsync ("publicGetTradesHistory",parameters);
    }

    public async Task<object> publicGetTicker (object parameters = null)
    {
        return await this.callAsync ("publicGetTicker",parameters);
    }

    public async Task<object> publicGetTickers (object parameters = null)
    {
        return await this.callAsync ("publicGetTickers",parameters);
    }

    public async Task<object> publicGetKlines (object parameters = null)
    {
        return await this.callAsync ("publicGetKlines",parameters);
    }

    public async Task<object> publicGetOpenInterest (object parameters = null)
    {
        return await this.callAsync ("publicGetOpenInterest",parameters);
    }

    public async Task<object> publicGetWallets (object parameters = null)
    {
        return await this.callAsync ("publicGetWallets",parameters);
    }

    public async Task<object> publicGetFundingRates (object parameters = null)
    {
        return await this.callAsync ("publicGetFundingRates",parameters);
    }

    public async Task<object> publicGetMarkPrices (object parameters = null)
    {
        return await this.callAsync ("publicGetMarkPrices",parameters);
    }

    public async Task<object> publicGetBorrowLendMarkets (object parameters = null)
    {
        return await this.callAsync ("publicGetBorrowLendMarkets",parameters);
    }

    public async Task<object> publicGetBorrowLendMarketsHistory (object parameters = null)
    {
        return await this.callAsync ("publicGetBorrowLendMarketsHistory",parameters);
    }

    public async Task<object> privateGetAccount (object parameters = null)
    {
        return await this.callAsync ("privateGetAccount",parameters);
    }

    public async Task<object> privateGetCapital (object parameters = null)
    {
        return await this.callAsync ("privateGetCapital",parameters);
    }

    public async Task<object> privateGetCapitalCollateral (object parameters = null)
    {
        return await this.callAsync ("privateGetCapitalCollateral",parameters);
    }

    public async Task<object> privateGetPosition (object parameters = null)
    {
        return await this.callAsync ("privateGetPosition",parameters);
    }

    public async Task<object> privateGetDepositAddress (object parameters = null)
    {
        return await this.callAsync ("privateGetDepositAddress",parameters);
    }

    public async Task<object> privateGetOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetOrders",parameters);
    }

    public async Task<object> privateGetOrder (object parameters = null)
    {
        return await this.callAsync ("privateGetOrder",parameters);
    }

    public async Task<object> privateGetFills (object parameters = null)
    {
        return await this.callAsync ("privateGetFills",parameters);
    }

    public async Task<object> privateGetPositions (object parameters = null)
    {
        return await this.callAsync ("privateGetPositions",parameters);
    }

    public async Task<object> privatePostOrders (object parameters = null)
    {
        return await this.callAsync ("privatePostOrders",parameters);
    }

    public async Task<object> privatePostOrdersExecute (object parameters = null)
    {
        return await this.callAsync ("privatePostOrdersExecute",parameters);
    }

    public async Task<object> privatePostCapitalDustConvert (object parameters = null)
    {
        return await this.callAsync ("privatePostCapitalDustConvert",parameters);
    }

    public async Task<object> privatePostBorrowLend (object parameters = null)
    {
        return await this.callAsync ("privatePostBorrowLend",parameters);
    }

    public async Task<object> privatePutAccount (object parameters = null)
    {
        return await this.callAsync ("privatePutAccount",parameters);
    }

    public async Task<object> privatePutOrdersOrderId (object parameters = null)
    {
        return await this.callAsync ("privatePutOrdersOrderId",parameters);
    }

    public async Task<object> privateDeleteOrder (object parameters = null)
    {
        return await this.callAsync ("privateDeleteOrder",parameters);
    }

    public async Task<object> privateDeleteOrders (object parameters = null)
    {
        return await this.callAsync ("privateDeleteOrders",parameters);
    }

    public async Task<object> wapiGetHistoryOrders (object parameters = null)
    {
        return await this.callAsync ("wapiGetHistoryOrders",parameters);
    }

    public async Task<object> wapiGetCapitalDeposits (object parameters = null)
    {
        return await this.callAsync ("wapiGetCapitalDeposits",parameters);
    }

    public async Task<object> wapiGetCapitalWithdrawals (object parameters = null)
    {
        return await this.callAsync ("wapiGetCapitalWithdrawals",parameters);
    }

    public async Task<object> wapiGetHistoryFunding (object parameters = null)
    {
        return await this.callAsync ("wapiGetHistoryFunding",parameters);
    }

    public async Task<object> wapiGetHistoryInterest (object parameters = null)
    {
        return await this.callAsync ("wapiGetHistoryInterest",parameters);
    }

    public async Task<object> wapiGetHistoryPnl (object parameters = null)
    {
        return await this.callAsync ("wapiGetHistoryPnl",parameters);
    }

    public async Task<object> wapiGetHistorySettlement (object parameters = null)
    {
        return await this.callAsync ("wapiGetHistorySettlement",parameters);
    }

    public async Task<object> wapiGetCapitalDepositAddress (object parameters = null)
    {
        return await this.callAsync ("wapiGetCapitalDepositAddress",parameters);
    }

    public async Task<object> wapiPostCapitalWithdraw (object parameters = null)
    {
        return await this.callAsync ("wapiPostCapitalWithdraw",parameters);
    }

}