// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicGetStatus (params?: {}): Promise<implicitReturnType>;
    publicGetTime (params?: {}): Promise<implicitReturnType>;
    publicGetAssets (params?: {}): Promise<implicitReturnType>;
    publicGetMarkets (params?: {}): Promise<implicitReturnType>;
    publicGetMarket (params?: {}): Promise<implicitReturnType>;
    publicGetDepth (params?: {}): Promise<implicitReturnType>;
    publicGetTrades (params?: {}): Promise<implicitReturnType>;
    publicGetTradesHistory (params?: {}): Promise<implicitReturnType>;
    publicGetTicker (params?: {}): Promise<implicitReturnType>;
    publicGetTickers (params?: {}): Promise<implicitReturnType>;
    publicGetKlines (params?: {}): Promise<implicitReturnType>;
    publicGetOpenInterest (params?: {}): Promise<implicitReturnType>;
    publicGetWallets (params?: {}): Promise<implicitReturnType>;
    publicGetFundingRates (params?: {}): Promise<implicitReturnType>;
    publicGetMarkPrices (params?: {}): Promise<implicitReturnType>;
    publicGetBorrowLendMarkets (params?: {}): Promise<implicitReturnType>;
    publicGetBorrowLendMarketsHistory (params?: {}): Promise<implicitReturnType>;
    privateGetAccount (params?: {}): Promise<implicitReturnType>;
    privateGetCapital (params?: {}): Promise<implicitReturnType>;
    privateGetCapitalCollateral (params?: {}): Promise<implicitReturnType>;
    privateGetPosition (params?: {}): Promise<implicitReturnType>;
    privateGetDepositAddress (params?: {}): Promise<implicitReturnType>;
    privateGetOrders (params?: {}): Promise<implicitReturnType>;
    privateGetOrder (params?: {}): Promise<implicitReturnType>;
    privateGetFills (params?: {}): Promise<implicitReturnType>;
    privateGetPositions (params?: {}): Promise<implicitReturnType>;
    privatePostOrders (params?: {}): Promise<implicitReturnType>;
    privatePostCapitalDustConvert (params?: {}): Promise<implicitReturnType>;
    privatePostBorrowLend (params?: {}): Promise<implicitReturnType>;
    privatePutAccount (params?: {}): Promise<implicitReturnType>;
    privatePutOrdersOrderId (params?: {}): Promise<implicitReturnType>;
    privateDeleteOrder (params?: {}): Promise<implicitReturnType>;
    privateDeleteOrders (params?: {}): Promise<implicitReturnType>;
    wapiGetHistoryOrders (params?: {}): Promise<implicitReturnType>;
    wapiGetCapitalDeposits (params?: {}): Promise<implicitReturnType>;
    wapiGetCapitalWithdrawals (params?: {}): Promise<implicitReturnType>;
    wapiGetHistoryFunding (params?: {}): Promise<implicitReturnType>;
    wapiGetHistoryInterest (params?: {}): Promise<implicitReturnType>;
    wapiGetHistoryPnl (params?: {}): Promise<implicitReturnType>;
    wapiGetHistorySettlement (params?: {}): Promise<implicitReturnType>;
    wapiGetCapitalDepositAddress (params?: {}): Promise<implicitReturnType>;
    wapiPostCapitalWithdraw (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
