// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *backpack) PublicGetStatus (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetStatus", args...)
}

func (this *backpack) PublicGetTime (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetTime", args...)
}

func (this *backpack) PublicGetAssets (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetAssets", args...)
}

func (this *backpack) PublicGetMarkets (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetMarkets", args...)
}

func (this *backpack) PublicGetMarket (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetMarket", args...)
}

func (this *backpack) PublicGetDepth (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetDepth", args...)
}

func (this *backpack) PublicGetTrades (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetTrades", args...)
}

func (this *backpack) PublicGetTradesHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetTradesHistory", args...)
}

func (this *backpack) PublicGetTicker (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetTicker", args...)
}

func (this *backpack) PublicGetTickers (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetTickers", args...)
}

func (this *backpack) PublicGetKlines (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetKlines", args...)
}

func (this *backpack) PublicGetOpenInterest (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetOpenInterest", args...)
}

func (this *backpack) PublicGetWallets (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetWallets", args...)
}

func (this *backpack) PublicGetFundingRates (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetFundingRates", args...)
}

func (this *backpack) PublicGetMarkPrices (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetMarkPrices", args...)
}

func (this *backpack) PublicGetBorrowLendMarkets (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetBorrowLendMarkets", args...)
}

func (this *backpack) PublicGetBorrowLendMarketsHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetBorrowLendMarketsHistory", args...)
}

func (this *backpack) PrivateGetAccount (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetAccount", args...)
}

func (this *backpack) PrivateGetCapital (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetCapital", args...)
}

func (this *backpack) PrivateGetCapitalCollateral (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetCapitalCollateral", args...)
}

func (this *backpack) PrivateGetPosition (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPosition", args...)
}

func (this *backpack) PrivateGetDepositAddress (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetDepositAddress", args...)
}

func (this *backpack) PrivateGetOrders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetOrders", args...)
}

func (this *backpack) PrivateGetOrder (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetOrder", args...)
}

func (this *backpack) PrivateGetFills (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetFills", args...)
}

func (this *backpack) PrivateGetPositions (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPositions", args...)
}

func (this *backpack) PrivatePostOrders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostOrders", args...)
}

func (this *backpack) PrivatePostOrdersExecute (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostOrdersExecute", args...)
}

func (this *backpack) PrivatePostCapitalDustConvert (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostCapitalDustConvert", args...)
}

func (this *backpack) PrivatePostBorrowLend (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostBorrowLend", args...)
}

func (this *backpack) PrivatePutAccount (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutAccount", args...)
}

func (this *backpack) PrivatePutOrdersOrderId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutOrdersOrderId", args...)
}

func (this *backpack) PrivateDeleteOrder (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteOrder", args...)
}

func (this *backpack) PrivateDeleteOrders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteOrders", args...)
}

func (this *backpack) WapiGetHistoryOrders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("wapiGetHistoryOrders", args...)
}

func (this *backpack) WapiGetCapitalDeposits (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("wapiGetCapitalDeposits", args...)
}

func (this *backpack) WapiGetCapitalWithdrawals (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("wapiGetCapitalWithdrawals", args...)
}

func (this *backpack) WapiGetHistoryFunding (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("wapiGetHistoryFunding", args...)
}

func (this *backpack) WapiGetHistoryInterest (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("wapiGetHistoryInterest", args...)
}

func (this *backpack) WapiGetHistoryPnl (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("wapiGetHistoryPnl", args...)
}

func (this *backpack) WapiGetHistorySettlement (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("wapiGetHistorySettlement", args...)
}

func (this *backpack) WapiGetCapitalDepositAddress (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("wapiGetCapitalDepositAddress", args...)
}

func (this *backpack) WapiPostCapitalWithdraw (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("wapiPostCapitalWithdraw", args...)
}
