from ccxt.base.types import Entry


class ImplicitAPI:
    public_get_status = publicGetStatus = Entry('status', 'public', 'GET', {'cost': 1})
    public_get_time = publicGetTime = Entry('time', 'public', 'GET', {'cost': 1})
    public_get_assets = publicGetAssets = Entry('assets', 'public', 'GET', {'cost': 1})
    public_get_markets = publicGetMarkets = Entry('markets', 'public', 'GET', {'cost': 1})
    public_get_market = publicGetMarket = Entry('market', 'public', 'GET', {'cost': 1})
    public_get_depth = publicGetDepth = Entry('depth', 'public', 'GET', {'cost': 1})
    public_get_trades = publicGetTrades = Entry('trades', 'public', 'GET', {'cost': 1})
    public_get_trades_history = publicGetTradesHistory = Entry('trades/history', 'public', 'GET', {'cost': 1})
    public_get_ticker = publicGetTicker = Entry('ticker', 'public', 'GET', {'cost': 1})
    public_get_tickers = publicGetTickers = Entry('tickers', 'public', 'GET', {'cost': 1})
    public_get_klines = publicGetKlines = Entry('klines', 'public', 'GET', {'cost': 1})
    public_get_openinterest = publicGetOpenInterest = Entry('openInterest', 'public', 'GET', {'cost': 1})
    public_get_wallets = publicGetWallets = Entry('wallets', 'public', 'GET', {'cost': 1})
    public_get_fundingrates = publicGetFundingRates = Entry('fundingRates', 'public', 'GET', {'cost': 1})
    public_get_markprices = publicGetMarkPrices = Entry('markPrices', 'public', 'GET', {'cost': 1})
    public_get_borrowlend_markets = publicGetBorrowLendMarkets = Entry('borrowLend/markets', 'public', 'GET', {'cost': 1})
    public_get_borrowlend_markets_history = publicGetBorrowLendMarketsHistory = Entry('borrowLend/markets/history', 'public', 'GET', {'cost': 1})
    private_get_account = privateGetAccount = Entry('account', 'private', 'GET', {'cost': 1})
    private_get_capital = privateGetCapital = Entry('capital', 'private', 'GET', {'cost': 1})
    private_get_capital_collateral = privateGetCapitalCollateral = Entry('capital/collateral', 'private', 'GET', {'cost': 1})
    private_get_position = privateGetPosition = Entry('position', 'private', 'GET', {'cost': 1})
    private_get_depositaddress = privateGetDepositAddress = Entry('depositAddress', 'private', 'GET', {'cost': 1})
    private_get_orders = privateGetOrders = Entry('orders', 'private', 'GET', {'cost': 1})
    private_get_order = privateGetOrder = Entry('order', 'private', 'GET', {'cost': 1})
    private_get_fills = privateGetFills = Entry('fills', 'private', 'GET', {'cost': 1})
    private_get_positions = privateGetPositions = Entry('positions', 'private', 'GET', {'cost': 1})
    private_post_orders = privatePostOrders = Entry('orders', 'private', 'POST', {'cost': 1})
    private_post_orders_execute = privatePostOrdersExecute = Entry('orders/execute', 'private', 'POST', {'cost': 1})
    private_post_capital_dust_convert = privatePostCapitalDustConvert = Entry('capital/dust/convert', 'private', 'POST', {'cost': 1})
    private_post_borrowlend = privatePostBorrowLend = Entry('borrowLend', 'private', 'POST', {'cost': 1})
    private_put_account = privatePutAccount = Entry('account', 'private', 'PUT', {'cost': 1})
    private_put_orders_orderid = privatePutOrdersOrderId = Entry('orders/{orderId}', 'private', 'PUT', {'cost': 1})
    private_delete_order = privateDeleteOrder = Entry('order', 'private', 'DELETE', {'cost': 1})
    private_delete_orders = privateDeleteOrders = Entry('orders', 'private', 'DELETE', {'cost': 1})
    wapi_get_history_orders = wapiGetHistoryOrders = Entry('history/orders', 'wapi', 'GET', {'cost': 1})
    wapi_get_capital_deposits = wapiGetCapitalDeposits = Entry('capital/deposits', 'wapi', 'GET', {'cost': 1})
    wapi_get_capital_withdrawals = wapiGetCapitalWithdrawals = Entry('capital/withdrawals', 'wapi', 'GET', {'cost': 1})
    wapi_get_history_funding = wapiGetHistoryFunding = Entry('history/funding', 'wapi', 'GET', {'cost': 1})
    wapi_get_history_interest = wapiGetHistoryInterest = Entry('history/interest', 'wapi', 'GET', {'cost': 1})
    wapi_get_history_pnl = wapiGetHistoryPnl = Entry('history/pnl', 'wapi', 'GET', {'cost': 1})
    wapi_get_history_settlement = wapiGetHistorySettlement = Entry('history/settlement', 'wapi', 'GET', {'cost': 1})
    wapi_get_capital_deposit_address = wapiGetCapitalDepositAddress = Entry('capital/deposit/address', 'wapi', 'GET', {'cost': 1})
    wapi_post_capital_withdraw = wapiPostCapitalWithdraw = Entry('capital/withdraw', 'wapi', 'POST', {'cost': 1})
