declare function testBackpackAuthentication(): Promise<void>;
declare function testBackpackMarketParsing(): Promise<void>;
declare function testBackpackOrderParsing(): Promise<void>;
declare function testBackpackTradeParsing(): Promise<void>;
declare function testBackpackBalanceParsing(): Promise<void>;
declare function testBackpackTickerParsing(): Promise<void>;
declare function testBackpackPositionParsing(): Promise<void>;
declare function testBackpackFundingRateParsing(): Promise<void>;
declare function testBackpackBorrowRateParsing(): Promise<void>;
declare function testBackpackDepositAddressParsing(): Promise<void>;
declare function testBackpackTradingFeesFormat(): Promise<void>;
declare function testBackpackConditionalOrderParsing(): Promise<void>;
declare function runBackpackTests(): Promise<void>;
export { testBackpackAuthentication, testBackpackMarketParsing, testBackpackOrderParsing, testBackpackTradeParsing, testBackpackBalanceParsing, testBackpackTickerParsing, testBackpackPositionParsing, testBackpackFundingRateParsing, testBackpackBorrowRateParsing, testBackpackDepositAddressParsing, testBackpackTradingFeesFormat, testBackpackConditionalOrderParsing, runBackpackTests, };
