<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class backpack extends \ccxt\Exchange {
    public function public_get_status($params = array()) {
        return $this->request('status', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_time($params = array()) {
        return $this->request('time', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_assets($params = array()) {
        return $this->request('assets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_markets($params = array()) {
        return $this->request('markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_market($params = array()) {
        return $this->request('market', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_depth($params = array()) {
        return $this->request('depth', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_trades($params = array()) {
        return $this->request('trades', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_trades_history($params = array()) {
        return $this->request('trades/history', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_ticker($params = array()) {
        return $this->request('ticker', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_tickers($params = array()) {
        return $this->request('tickers', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_klines($params = array()) {
        return $this->request('klines', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_openinterest($params = array()) {
        return $this->request('openInterest', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_wallets($params = array()) {
        return $this->request('wallets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_fundingrates($params = array()) {
        return $this->request('fundingRates', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_markprices($params = array()) {
        return $this->request('markPrices', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_borrowlend_markets($params = array()) {
        return $this->request('borrowLend/markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_borrowlend_markets_history($params = array()) {
        return $this->request('borrowLend/markets/history', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_account($params = array()) {
        return $this->request('account', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_capital($params = array()) {
        return $this->request('capital', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_capital_collateral($params = array()) {
        return $this->request('capital/collateral', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_position($params = array()) {
        return $this->request('position', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_depositaddress($params = array()) {
        return $this->request('depositAddress', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_orders($params = array()) {
        return $this->request('orders', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_order($params = array()) {
        return $this->request('order', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_fills($params = array()) {
        return $this->request('fills', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_positions($params = array()) {
        return $this->request('positions', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_post_orders($params = array()) {
        return $this->request('orders', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function private_post_orders_execute($params = array()) {
        return $this->request('orders/execute', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function private_post_capital_dust_convert($params = array()) {
        return $this->request('capital/dust/convert', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function private_post_borrowlend($params = array()) {
        return $this->request('borrowLend', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function private_put_account($params = array()) {
        return $this->request('account', 'private', 'PUT', $params, null, null, array("cost" => 1));
    }
    public function private_put_orders_orderid($params = array()) {
        return $this->request('orders/{orderId}', 'private', 'PUT', $params, null, null, array("cost" => 1));
    }
    public function private_delete_order($params = array()) {
        return $this->request('order', 'private', 'DELETE', $params, null, null, array("cost" => 1));
    }
    public function private_delete_orders($params = array()) {
        return $this->request('orders', 'private', 'DELETE', $params, null, null, array("cost" => 1));
    }
    public function wapi_get_history_orders($params = array()) {
        return $this->request('history/orders', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapi_get_capital_deposits($params = array()) {
        return $this->request('capital/deposits', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapi_get_capital_withdrawals($params = array()) {
        return $this->request('capital/withdrawals', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapi_get_history_funding($params = array()) {
        return $this->request('history/funding', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapi_get_history_interest($params = array()) {
        return $this->request('history/interest', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapi_get_history_pnl($params = array()) {
        return $this->request('history/pnl', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapi_get_history_settlement($params = array()) {
        return $this->request('history/settlement', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapi_get_capital_deposit_address($params = array()) {
        return $this->request('capital/deposit/address', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapi_post_capital_withdraw($params = array()) {
        return $this->request('capital/withdraw', 'wapi', 'POST', $params, null, null, array("cost" => 1));
    }
    public function publicGetStatus($params = array()) {
        return $this->request('status', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetTime($params = array()) {
        return $this->request('time', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetAssets($params = array()) {
        return $this->request('assets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetMarkets($params = array()) {
        return $this->request('markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetMarket($params = array()) {
        return $this->request('market', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetDepth($params = array()) {
        return $this->request('depth', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetTrades($params = array()) {
        return $this->request('trades', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetTradesHistory($params = array()) {
        return $this->request('trades/history', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetTicker($params = array()) {
        return $this->request('ticker', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetTickers($params = array()) {
        return $this->request('tickers', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetKlines($params = array()) {
        return $this->request('klines', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetOpenInterest($params = array()) {
        return $this->request('openInterest', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetWallets($params = array()) {
        return $this->request('wallets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetFundingRates($params = array()) {
        return $this->request('fundingRates', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetMarkPrices($params = array()) {
        return $this->request('markPrices', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetBorrowLendMarkets($params = array()) {
        return $this->request('borrowLend/markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetBorrowLendMarketsHistory($params = array()) {
        return $this->request('borrowLend/markets/history', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetAccount($params = array()) {
        return $this->request('account', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetCapital($params = array()) {
        return $this->request('capital', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetCapitalCollateral($params = array()) {
        return $this->request('capital/collateral', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetPosition($params = array()) {
        return $this->request('position', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetDepositAddress($params = array()) {
        return $this->request('depositAddress', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetOrders($params = array()) {
        return $this->request('orders', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetOrder($params = array()) {
        return $this->request('order', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetFills($params = array()) {
        return $this->request('fills', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetPositions($params = array()) {
        return $this->request('positions', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privatePostOrders($params = array()) {
        return $this->request('orders', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function privatePostOrdersExecute($params = array()) {
        return $this->request('orders/execute', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function privatePostCapitalDustConvert($params = array()) {
        return $this->request('capital/dust/convert', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function privatePostBorrowLend($params = array()) {
        return $this->request('borrowLend', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function privatePutAccount($params = array()) {
        return $this->request('account', 'private', 'PUT', $params, null, null, array("cost" => 1));
    }
    public function privatePutOrdersOrderId($params = array()) {
        return $this->request('orders/{orderId}', 'private', 'PUT', $params, null, null, array("cost" => 1));
    }
    public function privateDeleteOrder($params = array()) {
        return $this->request('order', 'private', 'DELETE', $params, null, null, array("cost" => 1));
    }
    public function privateDeleteOrders($params = array()) {
        return $this->request('orders', 'private', 'DELETE', $params, null, null, array("cost" => 1));
    }
    public function wapiGetHistoryOrders($params = array()) {
        return $this->request('history/orders', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapiGetCapitalDeposits($params = array()) {
        return $this->request('capital/deposits', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapiGetCapitalWithdrawals($params = array()) {
        return $this->request('capital/withdrawals', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapiGetHistoryFunding($params = array()) {
        return $this->request('history/funding', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapiGetHistoryInterest($params = array()) {
        return $this->request('history/interest', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapiGetHistoryPnl($params = array()) {
        return $this->request('history/pnl', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapiGetHistorySettlement($params = array()) {
        return $this->request('history/settlement', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapiGetCapitalDepositAddress($params = array()) {
        return $this->request('capital/deposit/address', 'wapi', 'GET', $params, null, null, array("cost" => 1));
    }
    public function wapiPostCapitalWithdraw($params = array()) {
        return $this->request('capital/withdraw', 'wapi', 'POST', $params, null, null, array("cost" => 1));
    }
}
